/* Error Constant */
export const ERRORS = {
  GET_ERRORS: 'GET_ERRORS',
}

/* Constant PORTOFOLIO */
export const PORTOFOLIOS = {
  LOAD: 'PORTOFOLIOS_LOAD',
  LOAD_SUCCESS: 'PORTOFOLIOS_LOAD_SUCCESS',
  CLEAR_SUCCESS: 'PORTOFOLIOS_CLEAR_SUCCESS',
  DETAIL_LOAD: 'PORTOFOLIOS_DETAIL_LOAD',
  DETAIL_LOAD_SUCCESS: 'PORTOFOLIOS_DETAIL_LOAD_SUCCESS',
  DETAIL_CLEAR_SUCCESS: 'PORTOFOLIOS_DETAIL_CLEAR_SUCCESS',
};

/* Constant LOGIN */
export const LOGIN = {
  POST: 'LOGIN_POST',
  POST_SUCCESS: 'LOGIN_POST_SUCCESS',
  CLEAR_SUCCESS: 'LOGIN_CLEAR_SUCCESS',
};
